services:
  tests:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "81:80"
    volumes:
       - ./src:/var/www/html
       - ./tests:/tests
    mem_limit: 256m
    cpus: '0.25'
